install.packages("dplyr")
install.packages("checkmate")
install.packages("asserthat")
install.packages("foreach")
install.packages("doParallel")
install.packages("numDeriv")
install.packages("mvtnorm")
install.packages("ggplot2")
install.packages("pracma")
install.packages("nloptr")
install.packages("tidyverse")
install.packages("MixGHD")
install.packages("bigstatsr")
install.packages("profvis")
install.packages("mmeln")
install.packages("mvnfast")
install.packages("ggpubr")



library(dplyr)
library(checkmate,asserthat)
library(foreach)
library(doParallel)
library(numDeriv)
library(mvtnorm)
library(ggplot2)
library(pracma)
library(nloptr)
library(tidyverse)
library(MixGHD)
library(bigstatsr)
library(profvis)
library(mmeln)
library(mvnfast)
library(ggpubr)
