Experiments <- list( 
  list(data = "Banknote", L = 4, U = 8, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 4, U = 32, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 4, U = 128, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 8, U = 32, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 8, U = 128, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 16, U = 32, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 16, U = 128, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 4, U = 128, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 8, U = 128, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Banknote", L = 16, U = 128, alp = 0.3, prio_t = "grid", prio_r = 100),
  
  list(data = "Breast_Cancer", L = 4, U = 16, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 4, U = 64, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 4, U = 256, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 8, U = 16, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 8, U = 64, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 8, U = 256, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 4, U = 16, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 4, U = 256, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 8, U = 16, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Breast_Cancer", L = 8, U = 256, alp = 0.3, prio_t = "grid", prio_r = 100),
  
  list(data = "Cassini", L = 6, U = 12, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 6, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 6, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 12, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 12, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 24, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 24, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 6, U = 192, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 12, U = 192, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Cassini", L = 24, U = 192, alp = 0.3, prio_t = "grid", prio_r = 20),
  
  list(data = "Ionosphere", L = 4, U = 16, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 4, U = 64, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 4, U = 256, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 8, U = 16, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 8, U = 64, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 8, U = 256, alp = 0.9, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 4, U = 16, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 8, U = 16, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 4, U = 256, alp = 0.3, prio_t = "grid", prio_r = 100),
  list(data = "Ionosphere", L = 8, U = 256, alp = 0.3, prio_t = "grid", prio_r = 100),
  
  list(data = "Iris", L = 6, U = 12, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 6, U = 64, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 6, U = 128, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 12, U = 64, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 12, U = 128, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 6, U = 12, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 6, U = 64, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 6, U = 128, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 12, U = 64, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Iris", L = 12, U = 128, alp = 0.3, prio_t = "grid", prio_r = 20),
  
  list(data = "Penguins", L = 6, U = 12, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 6, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 6, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 12, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 12, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 6, U = 12, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 6, U = 48, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 6, U = 192, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 12, U = 48, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Penguins", L = 12, U = 192, alp = 0.3, prio_t = "grid", prio_r = 20),
  
  list(data = "Simplex", L = 12, U = 24, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 12, U = 96, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 12, U = 384, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 24, U = 96, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 24, U = 384, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 48, U = 96, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 48, U = 384, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 12, U = 24, alp = 0.3, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 24, U = 96, alp = 0.3, prio_t = "grid", prio_r = 10),
  list(data = "Simplex", L = 48, U = 384, alp = 0.3, prio_t = "grid", prio_r = 10),
  
  list(data = "Simulated_A", L = 10, U = 20, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 10, U = 80, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 10, U = 320, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 20, U = 80, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 20, U = 320, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 40, U = 80, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 40, U = 320, alp = 0.9, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 10, U = 20, alp = 0.3, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 20, U = 80, alp = 0.3, prio_t = "grid", prio_r = 10),
  list(data = "Simulated_A", L = 40, U = 320, alp = 0.3, prio_t = "grid", prio_r = 10),
  
  list(data = "Waveform", L = 6, U = 12, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 6, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 6, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 12, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 12, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 24, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 24, U = 192, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 6, U = 12, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 12, U = 48, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Waveform", L = 24, U = 192, alp = 0.3, prio_t = "grid", prio_r = 20),
  
  list(data = "Wine", L = 6, U = 12, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 6, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 6, U = 96, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 12, U = 48, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 12, U = 96, alp = 0.9, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 6, U = 12, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 6, U = 48, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 6, U = 96, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 12, U = 48, alp = 0.3, prio_t = "grid", prio_r = 20),
  list(data = "Wine", L = 12, U = 96, alp = 0.3, prio_t = "grid", prio_r = 20)
)